export const PORTFOLIO_TOKENS = {
    REPOSITORIES: {
        PORTFOLIO: Symbol('PORTFOLIO.REPOSITORY.PORTFOLIO'),
        PORTFOLIO_HOLDING: Symbol('PORTFOLIO.REPOSITORY.PORTFOLIO_HOLDING'),
        PORTFOLIO_PROVIDER: Symbol('PORTFOLIO.REPOSITORY.PORTFOLIO_PROVIDER'),
    },

    HANDLERS: {
        QUERY: {
            LIST: Symbol('PORTFOLIO.QUERY.LIST'),
            DETAIL: Symbol('PORTFOLIO.QUERY.DETAIL'),
            OWNERSHIP: Symbol('PORTFOLIO.QUERY.OWNERSHIP'),
        },
        COMMAND: {
            CREATE: Symbol('PORTFOLIO.COMMAND.CREATE'),
            UPDATE: Symbol('PORTFOLIO.COMMAND.UPDATE'),
            DELETE: Symbol('PORTFOLIO.COMMAND.DELETE'),
        },
    },
};
