export const PORTFOLIO_TOKENS = {
    REPOSITORIES: {
        PORTFOLIO: Symbol('PORTFOLIO.REPOSITORY.PORTFOLIO'),
        PORTFOLIO_HOLDING: Symbol('PORTFOLIO.REPOSITORY.PORTFOLIO_HOLDING'),
        PORTFOLIO_PROVIDER: Symbol('PORTFOLIO.REPOSITORY.PORTFOLIO_PROVIDER'),
        TRANSACTION: Symbol('PORTFOLIO.REPOSITORY.TRANSACTION'),
    },

    HANDLERS: {
        QUERY: {
            LIST: Symbol('PORTFOLIO.QUERY.LIST'),
            DETAIL: Symbol('PORTFOLIO.QUERY.DETAIL'),
            OWNERSHIP: Symbol('PORTFOLIO.QUERY.OWNERSHIP'),
            TRANSACTION_LIST: Symbol('PORTFOLIO.QUERY.TRANSACTION_LIST'),
        },
        COMMAND: {
            CREATE: Symbol('PORTFOLIO.COMMAND.CREATE'),
            UPDATE: Symbol('PORTFOLIO.COMMAND.UPDATE'),
            DELETE: Symbol('PORTFOLIO.COMMAND.DELETE'),
            TRANSACTION_CREATE: Symbol('PORTFOLIO.COMMAND.TRANSACTION_CREATE'),
            TRANSACTION_UPDATE: Symbol('PORTFOLIO.COMMAND.TRANSACTION_UPDATE'),
            TRANSACTION_DELETE: Symbol('PORTFOLIO.COMMAND.TRANSACTION_DELETE'),
        },
    },
};
