--
-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA "public";


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA "public"; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA "public" IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Test; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE "public"."Test" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying
);


ALTER TABLE public."Test" OWNER TO postgres;

--
-- Name: TABLE "Test"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE "public"."Test" IS 'Test Only';


--
-- Name: Test_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE "public"."Test" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Test_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: Test; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY "public"."Test" ("id", "created_at", "name") FROM stdin;
1	2025-03-30 10:34:21.356126+00	Phuong 2
\.


--
-- Name: Test_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('"public"."Test_id_seq"', 1, true);


--
-- Name: Test Test_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY "public"."Test"
    ADD CONSTRAINT "Test_pkey" PRIMARY KEY ("id");


--
-- Name: Test; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE "public"."Test" ENABLE ROW LEVEL SECURITY;

--
-- PostgreSQL database dump complete
--

